### ISSUE TITLE
Can't download data.

### ISSUE THREAD

**Issue by lancejpollard** [paleobiodb/PBDB_changelog#22]
Data download is broken on the site.

<img width="857" alt="screen shot 2018-11-06 at 1 53 24 pm" src="https://user-images.githubusercontent.com/28718/48096179-6e4dc000-e1cb-11e8-88e4-ee20dd708d63.png">
<img width="913" alt="screen shot 2018-11-06 at 1 53 32 pm" src="https://user-images.githubusercontent.com/28718/48096177-6e4dc000-e1cb-11e8-814e-929c78ceff19.png">

**Comment by mmcclenn** [comment]
Can you tell me the values you entered on the download form? Or add a screenshot that shows them? I need to see what was on the form in order to reproduce the problem.

You can e-mail me directly at mmcclenn@geology.wisc.edu

**Comment by lancejpollard** [comment]
It was the default values, the first screenshot above is what was in the form.

<img width="1010" alt="screen shot 2018-11-06 at 5 13 29 pm" src="https://user-images.githubusercontent.com/28718/48104221-52f0ae00-e1e7-11e8-92dd-73d806c94cfd.png">

But anything I select errors as well. Seems like a frontend/jQuery error somewhere.

**Comment by mmcclenn** [comment]
Ah, I see now. That error message is actually spurious. I do need to deal with it, but it isn't breaking the form's functionality.

In order to download data, you need to fill in one or more of the fields on the form. If you actually want all occurrence records in the database, you need to check the box at the end of the "Select by Metadata" section. I should probably add some documentation to tell users about that.

Otherwise, you need to specify one or more taxon names, locations, geologic time periods, etc.

**Comment by mmcclenn** [comment]
Oops, I didn't read the last line of your comment. It is working fine for me, and presumably our other users since this is the first report I've had of a problem.

Can you tell me what web browser you are using?

**Comment by lancejpollard** [comment]
Yay that works, thank you!
