### ISSUE TITLE
Unhelpful FAQ answer re: contributing corrections

### ISSUE THREAD

**Issue by Circeus** [paleobiodb/PBDB_changelog#28]
I am not a specialist, merely a Wikispecies user with an interest in nomenclatural matters (and particularly in clearing out homonym that are an actual practical issue on a wiki vs. a database). Between Wikispecies and IRMNG, there are quite a few homonyms I wish to report as either having been formally replaced (e.g. Acaroceras/Acaroceratidae) or in need of replacement (e.g. Aaleniella Conti & Fischer, 1981).

However, the FAQ is... unhelpful on these matters. All it says is "suggested corrections regarding individual data records should be sent directly to the contributor who authorized the data". And how exactly is a user even supposed to do that? Email [everyone](https://paleobiodb.org/#/people) in turn hoping you eventually hit the right person?

**Comment by dwbapst** [comment]
Hi @Circeus, thanks for taking an interest in the Paleobiology Database.

I think you have misunderstood how the database works - everything in it is tied to a specific reference (which might be a journal article, or might be something a lot more gray), which is entered by an enterer, and the information once entered is checked and authorized by an authorizer. Often the enterer and the authorizer are the same person, but not always - one might have an undergrad entering data from the literature, and then checking and authorizing their entries.

Now, that a particular taxon is listed in the database as a valid taxon depends on a whole host of specific data records, such as what collections is that taxon reported from, to the taxonomic information entered that pertains to that taxon. All of that is made up of individual records, and all of those might have different enterers and authorizers - however figuring out who they are should be pretty easy by just checking the taxa / collections records themselves.

But the FAQ question you're referring to is about if a data record doesn't accurately reflect its reference. It sounds like to me that your corrections, if they have been published previously in the literature, should be considered probably new data records, if they haven't been entered already. In which case all you can do is let a specialist in that group who also is interested in fixing the taxonomy for those groups in the PBDB by entering new taxonomic references.

I hope that makes sense! 

(And to anyone reading this and who has been involved with the PBDB longer than I, I sincerely apologize if I'm talking complete nonsense and got it backwards!)

**Comment by Circeus** [comment]
I mean, I don't mind posting the material directly onto github if it's simpler for everyone involved, but I'd really like to be able to bring it to the attention of someone, except figuring out _who_, in the case of older taxon, is very very difficult for someone like me  who is not acquainted with the field.

**Comment by dwbapst** [comment]
The rough answer is it might be no one. 

So, let's try investigating one - so your problem is that the genus Aaleniella was already used before someone decided to use it as a gastropod taxon name. So, who entered/authorized the data, and presumably might care about keeping the gastropod taxonomy clean? So, let's try finding the genus in the classic view...

http://www.paleobiodb.org/classic/basicTaxonInfo?taxon_no=8516

If we look at the taxonomic history, we see that its part of Sepkoski 2002, which was the database that predated the PBDB. But its actual original references were added - so check out the original reference for the taxon...

http://www.paleobiodb.org/classic/displayReference?reference_no=63222

And we see...

![image](https://user-images.githubusercontent.com/1561903/71324158-1b070180-24a1-11ea-9248-9fe0019a7a3e.png)

See that bit that says `[PWagner/PWagner]`? That's the enterer/authorizer, which in this case is the the same person. (That should probably be labeled... at least a tooltip that that's the person who entered the data would be nice...) So, this means @peterjwagner3 entered it. Pete cares quite a lot about snails, so talk to him. ;D

But, and I apologize I didn't comment on this sooner, but the PBDB is rife with homonyms, the whole paleo literature is, and if there aren't references that rename the taxon in order to deal with the conflict, the PBDB really can't do much about it until such a reference exists. I don't know if its still true, but I remember being shown as a graduate student that there's a trilobite and a mammal with the same genus name, and both were even in the PBDB...

**Comment by Circeus** [comment]
Ironically, the situation you describe is exactly what's going on with Aaleniella, hence why I cite authorship for that name but not Acaroceras. To the best of my knowledge, the only database that has a specific system meant to detect homonyms (other than manual notes) is IRMNG, and Tony Rees, the may editor is rather completely swamped with things to update/add in it (I believe he told me he's currently trying to get Fungi updated to _2012_).

I don't think it's a Paleontology thing, but rather a side effect of the somewhat ivory tower nature of specialties relative to the breadth of nomenclature covered by the codes (and there are a _lot_ of specialties!). Botanists have ferreted a lot of their homonyms thanks to IPNI, but homonymy between vascular plants, fossil plants, fungi and algea still genera issues. (and apparently no one seems to be sure which come the Chromista even fall under XD)

**Comment by dwbapst** [comment]
Anyway, from a github point of view, I think your issue regarding that FAQ question has been 'solved' in the sense that the FAQ question you felt was being unhelpful wasn't really applicable to your situation (your issue isn't really with the accuracy of a specific data record that arises from a specific reference).
