### ISSUE TITLE
Donax bivalves classified as plants

### ISSUE THREAD

**Issue by ad-lord** [paleobiodb/PBDB_changelog#39]
Genus of bivalves, Donax (Linnaeus, 1758), are misclassified under Monocotyledoneae - Zingiberales - Zingiberidae. Due to this error, when you search for the family "Donacidae" on paleobiodb none of the Donax specimens are included in the results. When you search "Donax" and click on a collection/specimen, all the linked references in the database appear correct (state they are are bivalves/molluscs etc), but the donax species is listed under Monocotyledoneae.  E.g.
https://paleobiodb.org/classic/displayCollResults?taxon_no=142233&max_interval=Quaternary&country=Ireland&is_real_user=1&basic=yes&type=view&match_subgenera=1

**Comment by dwbapst** [comment]
Well, frankly... That's hilarious. But also a common issue. Sounds like a systematic revision is necessary.

**Comment by dwbapst** [comment]
Looks like the issue is the result of a taxonomic opinion just entered a few days ago, which placed Donax in the Arrow Roots.

Opinion record for Donax
The primary reference argues for this opinion:
M. Prasad 2008. Angiospermous fossil leaves from the Siwalik foreland basins and their palaeoclimatic implications The Palaeobotanist 57:177-21
- places Donax within Marantaceae
Authorizer: B. Allen Enterer: B. Allen Created: 2021-10-26 09:30:49 Modified: 2021-10-26 09:30:49

I am not sure why this taxonomic opinion is suppressing a newer one from 2010. It may be easier to ask B. Allen (I do not know them) to revise this taxonomic opinion. I presume this is another case where a botanical genus and a zoological genus have the same name.

**Comment by pnovack-gottshall** [comment]
The error was caused by a homonym of the bivalve Donax Linnaeus 1758 with the plant Donax Loureiro 1790, which had not been previously entered. Matthew Clapham resolved this by adding the homonym and adding a new opinion for the correct genus.

However, seems I can't "close" this issue?
